export const ActionTypes = {
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

	INIT_APP_DATA: "INIT_APP_DATA",

	INIT_DIRECTORIES: "INIT_DIRECTORIES",
	SET_CURRENT_DIRECTORY: "SET_CURRENT_DIRECTORY",
	SAVE_DIR_PROFILE: "SAVE_DIR_PROFILE",
	UPDATE_CORE_PROFILE: "UPDATE_CORE_PROFILE",
	GET_DIR_PROFILE: "GET_DIR_PROFILE",

	INIT_CONTACTS: "INIT_CONTACTS",
	SET_SELECTED_CONTACT: "SET_SELECTED_CONTACT",
	SEND_REQUEST_INFO: "SEND_REQUEST_INFO",
	RESPOND_TO_REQUEST: "RESPOND_TO_REQUEST",
	SHARE_INFO: "SHARE_INFO",
};
