export const ActionTypes = {
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

	INIT_APP_DATA: "INIT_APP_DATA",

	INIT_DIRECTORIES: "INIT_DIRECTORIES",
	SET_CURRENT_DIRECTORY: "SET_CURRENT_DIRECTORY",
	SAVE_DIR_PROFILE: "SAVE_DIR_PROFILE",
	SET_DIR_PROFILE: "SET_DIR_PROFILE",
	UPDATE_CORE_PROFILE: "UPDATE_CORE_PROFILE",
	GET_DIR_PROFILE: "GET_DIR_PROFILE",

	INIT_CONTACTS: "INIT_CONTACTS",
	SET_AGGREGATED_CONTACTS: "SET_AGGREGATED_CONTACTS",
	SET_ASKED_FROM_ME: "SET_ASKED_FROM_ME",
	SET_GIVEN_TO_ME: "SET_GIVEN_TO_ME",
	SET_WHAT_I_GAVE: "SET_WHAT_I_GAVE",
	SET_LATEST_SHARE: "SET_LATEST_SHARE",
	SET_SELECTED_CONTACT: "SET_SELECTED_CONTACT",
	SEND_REQUEST_INFO: "SEND_REQUEST_INFO",
	LOAD_SHARE_REQUESTS: "LOAD_REQUESTS",
	LOAD_SHARING: "LOAD_SHARING",
	LOAD_SENT_REQUESTS: "LOAD_SENT_REQUESTS",
	RESPOND_TO_REQUEST: "RESPOND_TO_REQUEST",
	SHARE_INFO: "SHARE_INFO",
};
